import * as fs from 'fs'
import * as path from 'path'

import { modifyMainApplication } from '../withAndroid'
import { withAttentive, type AttentivePluginProps } from '..'

// Pristine MainApplication.kt from expo-template-bare-minimum@57.0.8 — what
// `expo prebuild` generates before any plugin runs.
const fixture = fs.readFileSync(
  path.join(__dirname, 'fixtures', 'MainApplication.kt'),
  'utf8'
)

const props: AttentivePluginProps = { domain: 'games', mode: 'debug' }

const kt = (contents: string) => ({ contents, language: 'kt' })

describe('modifyMainApplication', () => {
  it('injects imports after the package line and init after super.onCreate()', () => {
    const result = modifyMainApplication(kt(fixture), props)

    expect(result).toMatch(
      /^package .+\n\/\/ @generated begin attentive-react-native-sdk-import/m
    )
    expect(result).toContain('import com.attentive.androidsdk.AttentiveConfig')
    expect(result).toContain('import com.attentive.androidsdk.AttentiveSdk')

    expect(result).toMatch(
      /super\.onCreate\(\)\n\/\/ @generated begin attentive-react-native-sdk-init/
    )
    expect(result).toContain('.domain("games")')
    expect(result).toContain('.mode(AttentiveConfig.Mode.DEBUG)')
    expect(result).toContain('AttentiveSdk.initialize(attentiveConfig)')

    expect(result).toContain(
      '// @generated end attentive-react-native-sdk-import'
    )
    expect(result).toContain(
      '// @generated end attentive-react-native-sdk-init'
    )

    expect(result).toMatchSnapshot()
  })

  it('maps production mode to AttentiveConfig.Mode.PRODUCTION', () => {
    const result = modifyMainApplication(kt(fixture), {
      domain: 'games',
      mode: 'production',
    })
    expect(result).toContain('.mode(AttentiveConfig.Mode.PRODUCTION)')
    expect(result).not.toContain('Mode.DEBUG')
  })

  it('is idempotent when re-applied with identical props', () => {
    const once = modifyMainApplication(kt(fixture), props)
    const twice = modifyMainApplication(kt(once), props)
    expect(twice).toBe(once)
  })

  it('replaces the generated block in place when props change', () => {
    const first = modifyMainApplication(kt(fixture), props)
    const second = modifyMainApplication(kt(first), {
      domain: 'shoes',
      mode: 'production',
    })

    expect(second).toContain('.domain("shoes")')
    expect(second).toContain('.mode(AttentiveConfig.Mode.PRODUCTION)')
    expect(second).not.toContain('.domain("games")')
    expect(second).not.toContain('Mode.DEBUG')

    // Exactly one of each block — updates must never accumulate duplicates.
    expect(
      second.match(/@generated begin attentive-react-native-sdk-init/g)
    ).toHaveLength(1)
    expect(
      second.match(/@generated begin attentive-react-native-sdk-import/g)
    ).toHaveLength(1)
  })

  it('skips and warns when MainApplication has a manual Attentive integration', () => {
    const manual = fixture.replace(
      'super.onCreate()',
      'super.onCreate()\n    AttentiveSdk.initialize(myOwnConfig)'
    )
    const warn = jest.spyOn(console, 'warn').mockImplementation(() => {})

    const result = modifyMainApplication(kt(manual), props)

    expect(result).toBe(manual)
    expect(warn).toHaveBeenCalledTimes(1)
    expect(warn.mock.calls[0][0]).toContain('not generated by this plugin')
    warn.mockRestore()
  })

  it('throws for a Java MainApplication (pre-SDK 50 template)', () => {
    const java =
      'package com.example;\n\npublic class MainApplication extends Application {}\n'
    expect(() =>
      modifyMainApplication({ contents: java, language: 'java' }, props)
    ).toThrow(/Expo SDK 50\+/)
  })

  it('skips (not throws) a Java file that already has a manual integration', () => {
    const javaManual =
      'package com.example;\n\nimport com.attentive.androidsdk.AttentiveSdk;\n\npublic class MainApplication extends Application {}\n'
    const warn = jest.spyOn(console, 'warn').mockImplementation(() => {})

    expect(
      modifyMainApplication({ contents: javaManual, language: 'java' }, props)
    ).toBe(javaManual)
    warn.mockRestore()
  })
})

describe('prop validation', () => {
  const config = {} as any

  it('throws a clear error when the plugin is used without options', () => {
    expect(() =>
      withAttentive(config, undefined as unknown as AttentivePluginProps)
    ).toThrow(/requires options.*app\.json/s)
  })

  it('throws a clear error when domain is missing', () => {
    expect(() =>
      withAttentive(config, { mode: 'debug' } as AttentivePluginProps)
    ).toThrow(/requires a `domain` option/)
  })

  it('throws a clear error on an invalid mode', () => {
    expect(() =>
      withAttentive(config, {
        domain: 'games',
        mode: 'staging',
      } as unknown as AttentivePluginProps)
    ).toThrow(/Invalid mode "staging"/)
  })
})

describe('generated Kotlin safety', () => {
  it('escapes quotes, backslashes, and dollar signs in the domain', () => {
    const result = modifyMainApplication(kt(fixture), {
      domain: 'my"weird\\$domain',
      mode: 'debug',
    })
    expect(result).toContain('.domain("my\\"weird\\\\\\$domain")')
  })

  it('defaults to Mode.PRODUCTION when mode is omitted', () => {
    const result = modifyMainApplication(kt(fixture), { domain: 'games' })
    expect(result).toContain('.mode(AttentiveConfig.Mode.PRODUCTION)')
  })
})

describe('manual integration alongside generated blocks', () => {
  it('skips and warns when manual Attentive code exists outside our blocks', () => {
    const generated = modifyMainApplication(kt(fixture), props)
    const mixed = generated.replace(
      'ApplicationLifecycleDispatcher.onApplicationCreate(this)',
      'AttentiveSdk.initialize(myManualConfig)\n    ApplicationLifecycleDispatcher.onApplicationCreate(this)'
    )
    const warn = jest.spyOn(console, 'warn').mockImplementation(() => {})

    const result = modifyMainApplication(kt(mixed), {
      domain: 'other-domain',
      mode: 'production',
    })

    expect(result).toBe(mixed)
    expect(warn).toHaveBeenCalledTimes(1)
    warn.mockRestore()
  })
})

describe('mergeContents resolution on Expo SDK 50–53', () => {
  // Expo SDK 50–53 do not re-export CodeGenerator from 'expo/config-plugins';
  // the plugin must fall back to resolving @expo/config-plugins' internal
  // generateCode module through the app's expo package. Simulate the pre-54
  // export surface by masking CodeGenerator on the mocked module.
  it('falls back to the deep import when CodeGenerator is not exported', () => {
    let result = ''
    jest.isolateModules(() => {
      const actual = jest.requireActual('expo/config-plugins')
      jest.doMock('expo/config-plugins', () => ({
        ...actual,
        CodeGenerator: undefined,
      }))
      const { modifyMainApplication: modify } = require('../withAndroid')
      result = modify(kt(fixture), props)
    })
    jest.dontMock('expo/config-plugins')

    expect(result).toContain(
      '// @generated begin attentive-react-native-sdk-init'
    )
    expect(result).toContain('.domain("games")')
    expect(result).toContain('AttentiveSdk.initialize(attentiveConfig)')
  })
})
