import type { CodeGenerator, ConfigPlugin } from 'expo/config-plugins'
import { type AttentivePluginProps } from '.'
import {
  configPlugins,
  requireFromExpoConfigPlugins,
} from './expoConfigPlugins'

const { withMainApplication } = configPlugins

type MergeContentsFn = typeof CodeGenerator.mergeContents

// The public re-export of the generateCode utils (the CodeGenerator
// namespace) only exists from Expo SDK 54; on SDK 50–53 mergeContents is
// reachable only via @expo/config-plugins' internal build path. We resolve
// that path *through the app's expo package*: expo declares
// @expo/config-plugins as a dependency, so the edge is valid under every
// package manager, including pnpm's strict layout. SDK 50–53 are frozen on
// npm, so the internal path cannot move for the only versions that use it.
function resolveMergeContents(): MergeContentsFn {
  if (configPlugins.CodeGenerator?.mergeContents) {
    return configPlugins.CodeGenerator.mergeContents
  }
  return requireFromExpoConfigPlugins(
    '@expo/config-plugins/build/utils/generateCode'
  ).mergeContents
}

const ATTENTIVE_TAG = 'attentive-react-native-sdk'

function generateMode(props: AttentivePluginProps): string {
  const mode =
    props.mode === 'debug'
      ? 'AttentiveConfig.Mode.DEBUG'
      : 'AttentiveConfig.Mode.PRODUCTION'

  return mode
}

function generateInitCode(props: AttentivePluginProps): string {
  const lines = [
    'val attentiveConfig = AttentiveConfig.Builder()',
    `  .applicationContext(this)`,
    `  .domain("${props.domain}")`,
    `  .mode(${generateMode(props)})`,
    `  .build()`,
    `AttentiveSdk.initialize(attentiveConfig)`,
  ]

  return lines.join('\n    ')
}

function getImports(): string {
  const imports = [
    'import com.attentive.androidsdk.AttentiveConfig',
    'import com.attentive.androidsdk.AttentiveSdk',
  ]

  return imports.join('\n')
}

// Matches the header mergeContents writes for both of our tagged blocks
// (`${ATTENTIVE_TAG}-import` and `${ATTENTIVE_TAG}-init`).
const GENERATED_BLOCK_MARKER = `@generated begin ${ATTENTIVE_TAG}-`

// True when MainApplication references the Attentive SDK outside a block this
// plugin generated — i.e. the app integrated manually. Blocks we generated
// don't count: mergeContents replaces those on its own when props change.
function hasManualAttentiveInit(contents: string): boolean {
  return (
    !contents.includes(GENERATED_BLOCK_MARKER) &&
    (contents.includes('AttentiveConfig') || contents.includes('AttentiveSdk'))
  )
}

function addAttentiveToApplication(
  contents: string,
  props: AttentivePluginProps
) {
  const mergeContents = resolveMergeContents()

  const withImports = mergeContents({
    src: contents,
    newSrc: getImports(),
    anchor: /^package .+$/m,
    offset: 1,
    tag: `${ATTENTIVE_TAG}-import`,
    comment: '//',
  })

  const initCode = generateInitCode(props)

  let result = withImports.contents

  const withInit = mergeContents({
    src: result,
    newSrc: `\n    ${initCode}\n`,
    anchor: /super\.onCreate\(\)/,
    offset: 1,
    tag: `${ATTENTIVE_TAG}-init`,
    comment: '//',
  })

  result = withInit.contents

  return result
}

// Pure core of the mod, extracted so tests can exercise it without Expo's
// prebuild machinery. Returns the (possibly unchanged) file contents.
export function modifyMainApplication(
  modResults: { contents: string; language: string },
  props: AttentivePluginProps
): string {
  const { contents, language } = modResults

  if (hasManualAttentiveInit(contents)) {
    console.warn(
      '[attentive-react-native-sdk] Found an existing Attentive integration ' +
        'in MainApplication that was not generated by this plugin. Skipping ' +
        'code injection — remove the manual initialization to let the plugin ' +
        'manage it.'
    )
    return contents
  }

  if (language !== 'kt') {
    throw new Error(
      `[attentive-react-native-sdk] requires Expo SDK 50+ / Kotlin MainApplication. ` +
        `Initialize manually per README otherwise.`
    )
  }

  return addAttentiveToApplication(contents, props)
}

export const withAndroid: ConfigPlugin<AttentivePluginProps> = (
  config,
  props
) => {
  return withMainApplication(config, (modConfig) => {
    modConfig.modResults.contents = modifyMainApplication(
      modConfig.modResults,
      props
    )
    return modConfig
  })
}
