#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# reset.sh – Clean and reinstall all Bonni project dependencies.
#
# Usage:
#   ./reset.sh          Standard clean: preserves expensive build caches so
#                       the next build is fast (Gradle dep cache, CMake outputs).
#
#   ./reset.sh --full   Deep clean: wipes everything including the global Gradle
#                       dependency cache and CMake native-build outputs.
#                       Use when you need a truly pristine state (e.g. after
#                       changing native SDK versions or diagnosing cache corruption).
#
# Expensive artefacts preserved by the standard clean:
#   ~/.gradle/caches          – downloaded Android/Gradle dependencies
#   android/app/build/.cxx/   – CMake / native-code compilation outputs
#   android/autolinking.json  – rnc-cli config snapshot (regenerated by postinstall)
# ---------------------------------------------------------------------------

set -euo pipefail

FULL_CLEAN=false
for arg in "$@"; do
  case "$arg" in
    --full) FULL_CLEAN=true ;;
    *) echo "Unknown argument: $arg  (supported: --full)" >&2; exit 1 ;;
  esac
done

if [ "$FULL_CLEAN" = true ]; then
  echo ""
  echo "🔥 ************************************"
  echo "🔥 * FULL clean — wiping all caches   *"
  echo "🔥 ************************************"
else
  echo ""
  echo "🧹 ************************************"
  echo "🧹 * Standard clean (caches preserved)*"
  echo "🧹 ************************************"
fi
echo ""

# ── General ────────────────────────────────────────────────────────────────
echo "▸ General cleanup"
watchman watch-del-all
rm -rf "$TMPDIR/react-"* "$TMPDIR/npm-"*

# ── Android ────────────────────────────────────────────────────────────────
echo "▸ Android cleanup"
cd android || exit 1

# Stop any running Gradle daemons so they don't hold file locks.
pkill -f gradle-daemon 2>/dev/null || true

# Project-level Gradle cache (.gradle/) is always safe to delete — it rebuilds
# quickly from the global cache which we optionally preserve.
rm -rf build .gradle

if [ "$FULL_CLEAN" = true ]; then
  echo "  Removing app/build (including CMake outputs)…"
  rm -rf app/build
  echo "  Removing ~/.gradle/caches (Gradle dependency cache)…"
  rm -rf ~/.gradle/caches
else
  echo "  Removing app/build except CMake outputs (.cxx)…"
  # Delete every direct child of app/build except the .cxx directory which
  # holds expensive CMake / native compilation results.
  if [ -d "app/build" ]; then
    find app/build -mindepth 1 -maxdepth 1 ! -name '.cxx' -exec rm -rf {} +
  fi
  # Always clear Gradle transforms: these are re-processed AAR/JAR files.
  # They can get corrupted after an interrupted build and cause AAPT2 daemon
  # failures on the next run.  Gradle rebuilds them quickly from the cached
  # Maven artifacts, so clearing them is safe and cheap.
  echo "  Clearing Gradle transforms cache…"
  GRADLE_VERSION=$(cat gradle/wrapper/gradle-wrapper.properties | grep distributionUrl | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1)
  rm -rf ~/.gradle/caches/"${GRADLE_VERSION}"/transforms
fi

# Always stop old daemons so they pick up any changed build settings.
rm -rf ~/.gradle/daemon

cd ..

# ── iOS ────────────────────────────────────────────────────────────────────
echo "▸ iOS cleanup"
cd ios || exit 1
rm -rf Pods build Podfile.lock
rm -rf ~/Library/Caches/CocoaPods

if [ "$FULL_CLEAN" = true ]; then
  echo "  Removing Xcode DerivedData…"
  rm -rf ~/Library/Developer/Xcode/DerivedData 2>/dev/null || true
fi

cd ..

# ── npm ────────────────────────────────────────────────────────────────────
echo "▸ npm: removing node_modules and reinstalling"
npm cache clean --force
rm -rf node_modules

# npm install triggers the postinstall script, which:
#   1. Applies patches via patch-package
#   2. Regenerates android/autolinking.json via rnc-cli config
# This runs fast on a warm disk (node_modules files were just written by npm).
npm install

# ── iOS Pods ───────────────────────────────────────────────────────────────
./install-pods.sh

echo ""
echo "✅ Done!  Run \`npm run android\` or \`npm run ios\` to build."
exit 0
